spring:
  application:
    name: notification-service
data:
   mongodb:
     uri: ${SPRING_DATA_MONGODB_URI:mongodb://mongodb:27017/glowkart_notification}
     database: ${SPRING_DATA_MONGODB_DATABASE:glowkart_notification}

server:
  port: ${SERVER_PORT:9090}  # Default port 8090, can override via env

# AWS SQS Configuration
aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: ap-south-1
  sqs:
    notification-queue-url: ${SQS_NOTIFICATION_QUEUE_URL}
    dlq-url: ${SQS_DLQ_URL}

# Firebase FCM Configuration
firebase:
  service-account-path: ${FIREBASE_SERVICE_ACCOUNT:src/main/resources/firebase-service-account.json}

# Eureka configuration for service discovery
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://eureka-server:8761/eureka/}
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

# Logging
logging:
  level:
    com.glowkart.notification: INFO
    org.springframework.web: INFO
    software.amazon.awssdk: WARN

# Optional: Feign (if calling other microservices)
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic