spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      server:
        webflux:
          routes:
            # 0: Admin Service
            - id: admin-service
              uri: lb://admin-service
              predicates:
                - Path=/admin/**

            # 1: Clinic Admin Service
            - id: clinic-admin-service
              uri: lb://clinicadmin-service
              predicates:
                - Path=/clinic-admin/**

            # 2: Customer Service
            - id: customer-service
              uri: lb://customer-service
              predicates:
                - Path=/api/**

            # 3: Onboarding Service
            - id: onboarding-service
              uri: lb://onboarding-service
              predicates:
                - Path=/onboard/**

            # 4: Procedure Service
            - id: procedure-service
              uri: lb://procedure-service
              predicates:
                - Path=/procedures/**

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "http://localhost:3000,http://35.154.152.61:3000,http://35.154.152.61:4000,http://35.154.152.61:5000"
                allowedMethods: "GET,POST,PUT,DELETE"
                allowedHeaders: "*"
                allowCredentials: true

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG