export const aptData = [
  {
    appointmentId: 'APT-1010',
    bookingId: 'BKG-5010',
    patientId: 'PAT-9010',
    patientName: 'Lavanya Iyer',
    patientAge: 33,
    patientAddress: 'Whitefield, Bangalore',
    clinicId: 'CLN-110',
    clinicName: 'Elite Skin Clinic',
    clinicmobileNumber: '9876500010',
    customermobileNumber: '9876543119',
    clinicMapLink: 'https://maps.example.com/clinic10',
    service: {
      type: 'Package',
      serviceId: 'PKG-2005',
      serviceName: 'Bridal Skin Glow Package',
    },
    serviceDate: '2025-12-24',
    status: 'Completed',
    paidAmount: '500',
    consultationFee: '300',
  },
  {
    appointmentId: 'APT-1001',
    bookingId: 'BKG-5001',
    patientId: 'PAT-9001',
    patientName: 'Rahul Sharma',
    patientAge: 29,
    patientAddress: 'Indiranagar, Bangalore',
    clinicId: 'CLN-101',
    clinicName: "Neeha's Glow Kart Clinic",
    clinicmobileNumber: '9876500001',
    customermobileNumber: '9876543210',
    clinicMapLink: 'https://maps.example.com/clinic1',
    service: {
      type: 'Package',
      serviceId: 'PKG-2001',
      serviceName: 'Premium Glow Skin Package',
    },
    serviceDate: '2025-12-15',
    status: 'Pending',
    paidAmount: '500',
    consultationFee: '300',
  },
  {
    appointmentId: 'APT-1002',
    bookingId: 'BKG-5002',
    patientId: 'PAT-9002',
    patientName: 'Sneha Reddy',
    patientAge: 34,
    patientAddress: 'Hitech City, Hyderabad',
    clinicId: 'CLN-102',
    clinicName: 'Skin & Shine Clinic',
    clinicmobileNumber: '9876500002',
    customermobileNumber: '9876543221',
    clinicMapLink: 'https://maps.example.com/clinic2',
    service: {
      type: 'Procedure',
      serviceId: 'PRC-3001',
      serviceName: 'Laser Hair Removal - Arms',
    },
    serviceDate: '2025-12-16',
    status: 'Completed',
    paidAmount: '500',
    consultationFee: '300',
  },
  {
    appointmentId: 'APT-1003',
    bookingId: 'BKG-5003',
    patientId: 'PAT-9003',
    patientName: 'Arjun Patel',
    patientAge: 41,
    patientAddress: 'Andheri West, Mumbai',
    clinicId: 'CLN-103',
    clinicName: 'GlowPlus Aesthetic Center',
    clinicmobileNumber: '9876500003',
    customermobileNumber: '9876543332',
    clinicMapLink: 'https://maps.example.com/clinic3',
    service: {
      type: 'Package',
      serviceId: 'PKG-2002',
      serviceName: 'Anti-Aging Treatment Package',
    },
    serviceDate: '2025-12-17',
    status: 'Pending',
    paidAmount: '500',
    consultationFee: '300',
  },
  {
    appointmentId: 'APT-1004',
    bookingId: 'BKG-5004',
    patientId: 'PAT-9004',
    patientName: 'Meera Nair',
    patientAge: 27,
    patientAddress: 'Kakkanad, Kochi',
    clinicId: 'CLN-104',
    clinicName: 'Skin Aura Clinic',
    clinicmobileNumber: '9876500004',
    customermobileNumber: '9876543443',
    clinicMapLink: 'https://maps.example.com/clinic4',
    service: {
      type: 'Procedure',
      serviceId: 'PRC-3002',
      serviceName: 'Chemical Peel - Brightening',
    },
    serviceDate: '2025-12-18',
    status: 'Completed',
    paidAmount: '500',
    consultationFee: '300',
  },
  {
    appointmentId: 'APT-1005',
    bookingId: 'BKG-5005',
    patientId: 'PAT-9005',
    patientName: 'Vikram Singh',
    patientAge: 36,
    patientAddress: 'Sector 62, Noida',
    clinicId: 'CLN-105',
    clinicName: 'DermaCare Clinic',
    clinicmobileNumber: '9876500005',
    customermobileNumber: '9876543554',
    clinicMapLink: 'https://maps.example.com/clinic5',
    service: {
      type: 'Package',
      serviceId: 'PKG-2003',
      serviceName: 'Acne Scar Removal Package',
    },
    serviceDate: '2025-12-19',
    status: 'Pending',
    paidAmount: '500',
    consultationFee: '300',
  },
  {
    appointmentId: 'APT-1006',
    bookingId: 'BKG-5006',
    patientId: 'PAT-9006',
    patientName: 'Priya Verma',
    patientAge: 31,
    patientAddress: 'Baner, Pune',
    clinicId: 'CLN-106',
    clinicName: 'Glow Essence Clinic',
    clinicmobileNumber: '9876500006',
    customermobileNumber: '9876543665',
    clinicMapLink: 'https://maps.example.com/clinic6',
    service: {
      type: 'Procedure',
      serviceId: 'PRC-3003',
      serviceName: 'Hydrafacial Treatment',
    },
    serviceDate: '2025-12-20',
    status: 'Completed',
    paidAmount: '500',
    consultationFee: '300',
  },
  {
    appointmentId: 'APT-1007',
    bookingId: 'BKG-5007',
    patientId: 'PAT-9007',
    patientName: 'Karan Johar',
    patientAge: 38,
    patientAddress: 'Salt Lake, Kolkata',
    clinicId: 'CLN-107',
    clinicName: 'Rejuvenate Skin Center',
    clinicmobileNumber: '9876500007',
    customermobileNumber: '9876543776',
    clinicMapLink: 'https://maps.example.com/clinic7',
    service: {
      type: 'Package',
      serviceId: 'PKG-2004',
      serviceName: 'Full Body Polishing Package',
    },
    serviceDate: '2025-12-21',
    status: 'Pending',
    paidAmount: '500',
    consultationFee: '300',
  },
  {
    appointmentId: 'APT-1008',
    bookingId: 'BKG-5008',
    patientId: 'PAT-9008',
    patientName: 'Aditi Rao',
    patientAge: 25,
    patientAddress: 'Anna Nagar, Chennai',
    clinicId: 'CLN-108',
    clinicName: 'Radiant Derma Studio',
    clinicmobileNumber: '9876500008',
    customermobileNumber: '9876543887',
    clinicMapLink: 'https://maps.example.com/clinic8',
    service: {
      type: 'Procedure',
      serviceId: 'PRC-3004',
      serviceName: 'Skin Whitening Laser',
    },
    serviceDate: '2025-12-22',
    status: 'Completed',
    paidAmount: '500',
    consultationFee: '300',
  },
  {
    appointmentId: 'APT-1009',
    bookingId: 'BKG-5009',
    patientId: 'PAT-9009',
    patientName: 'Suresh Kumar',
    patientAge: 45,
    patientAddress: 'Gachibowli, Hyderabad',
    clinicId: 'CLN-109',
    clinicName: 'Urban Skin Lab',
    clinicmobileNumber: '9876500009',
    customermobileNumber: '9876543998',
    clinicMapLink: 'https://maps.example.com/clinic9',
    service: {
      type: 'Procedure',
      serviceId: 'PRC-3005',
      serviceName: 'Mole Removal Treatment',
    },
    serviceDate: '2025-12-23',
    status: 'Pending',
    paidAmount: '500',
    consultationFee: '300',
  },
]
