spring:
  application:
    name: booking-service
  cloud:
    config:
      uri: http://config-server:8888  # Config Server URI

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://mongodb:27017/bookingdb}
      database: ${SPRING_DATA_MONGODB_DATABASE:bookingdb}

server:
  port: 8087

# Feign configuration
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

# Eureka configuration
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
